name: ebtikar_ai_task
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.1
  get: ^4.6.6
  shared_preferences: ^2.3.5
  http: ^1.3.0
  flutter_dotenv: ^5.2.1
  share_plus: ^10.1.4
  loading_plus: ^2.0.2
  firebase_messaging: ^15.2.1
  package_info_plus: ^8.1.3
  internet_connection_checker: ^3.0.1
  upgrader: ^11.3.1
  in_app_review: ^2.0.10
  encrypt: ^5.0.3
  flutter_svg: ^2.0.17
  url_launcher: ^6.3.1
  firebase_crashlytics: ^4.3.1
  firebase_analytics: ^11.4.1
  flutter_local_notifications: ^18.0.1
  font_awesome_flutter: ^10.8.0
  skeletonizer: ^1.4.3
  restart_app: ^1.3.2
  country_picker: ^2.0.27
  pinput: ^5.0.1

dependency_overrides:
  intl: 0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4
  import_sorter: ^4.6.0
  rename: ^3.0.2

########## import_sorter ##########
import_sorter:
  emojis: false
  comments: false

# dart run import_sorter:main
########## import_sorter ##########

########## rename ##########
#  dart pub global activate rename
#  rename getAppName --targets ios,android,macos,windows,linux
#  rename setAppName --targets ios,android,macos,windows,linux --value "Ebtikar AI Task"
#  rename getBundleId --targets ios,android,macos,windows,linux
#  rename setBundleId --targets ios,android,macos,windows,linux --value "com.assaf.ebtikarAITask"

########## rename ##########

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  remove_alpha_ios: true

#  flutter pub get
#  dart run flutter_launcher_icons

########## flutter_launcher_icons ##########

########## flutter_native_splash ##########
flutter_native_splash:
  color: "#000000"
  icon_background_color: "#000000"
  android_12:
    color: "#000000"

  # dart run flutter_native_splash:create
  # dart run flutter_native_splash:remove
########## flutter_native_splash ##########

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
    - assets/images/
    - assets/icons/
    # - assets/gifs/
    # - assets/sounds/
    # - assets/videos/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
          
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Tajawal/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal/Tajawal-ExtraLight.ttf
          weight: 300

    - family: Changa
      fonts:
        - asset: assets/fonts/Changa/Changa-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Changa/Changa-Bold.ttf
          weight: 700
        - asset: assets/fonts/Changa/Changa-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Changa/Changa-Medium.ttf
          weight: 500
        - asset: assets/fonts/Changa/Changa-Regular.ttf
          weight: 400
        - asset: assets/fonts/Changa/Changa-Light.ttf
          weight: 300
        - asset: assets/fonts/Changa/Changa-ExtraLight.ttf
          weight: 300
