export 'dart:async';
export 'dart:convert';
export 'dart:io' hide HeaderValue;
export 'package:ebtikar_ai_task/models/local_model/nav_item_model.dart';
export 'package:ebtikar_ai_task/resources/managers/size_manager.dart';

export 'package:flutter/cupertino.dart' show CupertinoAlertDialog;
export 'package:flutter/material.dart';
export 'package:flutter/scheduler.dart' hide Priority;
export 'package:flutter/services.dart';
export 'package:ebtikar_ai_task/modules/saved_videos/view/saved_videos_view.dart';
export 'package:ebtikar_ai_task/modules/search/view/search_view.dart';
export 'package:firebase_messaging/firebase_messaging.dart';
export 'package:flutter_dotenv/flutter_dotenv.dart';
export 'package:flutter_gen/gen_l10n/app_localizations.dart';
export 'package:flutter_local_notifications/flutter_local_notifications.dart';
export 'package:flutter_svg/flutter_svg.dart';
export 'package:ebtikar_ai_task/modules/settings/widgets/setting_divider.dart';
export 'package:ebtikar_ai_task/modules/profile/controller/profile_controller.dart';
export 'package:ebtikar_ai_task/resources/globals.dart';
export 'package:font_awesome_flutter/font_awesome_flutter.dart';
export 'package:get/get.dart';
export 'package:pinput/pinput.dart';
export 'package:country_picker/country_picker.dart';
export 'package:ebtikar_ai_task/modules/profile/binding/profile_binding.dart';
export 'package:ebtikar_ai_task/modules/profile/view/profile_view.dart';
export 'package:ebtikar_ai_task/modules/settings/bindings/settings_binding.dart';
export 'package:ebtikar_ai_task/modules/settings/views/settings_view.dart';
export 'package:skeletonizer/skeletonizer.dart';
export 'package:in_app_review/in_app_review.dart';
export 'package:internet_connection_checker/internet_connection_checker.dart';
export 'package:intl/intl.dart' hide TextDirection;
export 'package:loading_plus/loading_plus.dart';
export 'package:package_info_plus/package_info_plus.dart';
export 'package:share_plus/share_plus.dart';
export 'package:shared_preferences/shared_preferences.dart';
export 'package:upgrader/upgrader.dart' hide ambiguate;
export 'package:url_launcher/url_launcher.dart';

export 'package:ebtikar_ai_task/main.dart';
export 'package:ebtikar_ai_task/models/data_model/user_model.dart';
export 'package:ebtikar_ai_task/models/local_model/language_model.dart';

export 'package:ebtikar_ai_task/modules/connection_error/binding/connection_error_binding.dart';
export 'package:ebtikar_ai_task/modules/connection_error/controller/connection_error_controller.dart';
export 'package:ebtikar_ai_task/modules/connection_error/view/connection_error_view.dart';
export 'package:ebtikar_ai_task/modules/home/controller/home_controller.dart';
export 'package:ebtikar_ai_task/modules/home/view/home_view.dart';
export 'package:ebtikar_ai_task/modules/navigation/binding/navigation_binding.dart';
export 'package:ebtikar_ai_task/modules/navigation/controller/navigation_controller.dart';
export 'package:ebtikar_ai_task/modules/navigation/view/navigation_view.dart';
export 'package:ebtikar_ai_task/modules/settings/controllers/settings_controller.dart';
export 'package:ebtikar_ai_task/modules/splash/binding/splash_binding.dart';
export 'package:ebtikar_ai_task/modules/splash/controller/splash_controller.dart';
export 'package:ebtikar_ai_task/modules/splash/view/splash_view.dart';
export 'package:ebtikar_ai_task/resources/components.dart';
export 'package:ebtikar_ai_task/resources/global_controllers/language_controller.dart';
export 'package:ebtikar_ai_task/resources/managers/assets_manager.dart';
export 'package:ebtikar_ai_task/resources/managers/constants_manager.dart';
export 'package:ebtikar_ai_task/resources/managers/exception_manager.dart';
export 'package:ebtikar_ai_task/resources/managers/fonts_manager.dart';
export 'package:ebtikar_ai_task/resources/managers/routes_manager.dart';
export 'package:ebtikar_ai_task/repositories/video/video_repository.dart';
export 'package:ebtikar_ai_task/models/data_model/video_model.dart';
export 'package:ebtikar_ai_task/repositories/video/video_api.dart';
export 'package:shimmer/shimmer.dart';
export 'package:video_player/video_player.dart';
export 'package:cached_network_image/cached_network_image.dart' hide timeDilation;
export 'package:ebtikar_ai_task/models/enums/category_enum.dart';
export 'package:ebtikar_ai_task/repositories/api_services.dart';
export 'package:ebtikar_ai_task/resources/widgets/video/controls_overlay.dart';
export 'package:ebtikar_ai_task/resources/widgets/video/video_indicator.dart';
export 'package:readmore/readmore.dart';
export 'package:ebtikar_ai_task/modules/saved_videos/controller/saved_videos_controller.dart';
export 'package:ebtikar_ai_task/resources/widgets/video/videos_list.dart';
export 'package:ebtikar_ai_task/resources/widgets/video/empty_videos_list.dart';
export 'package:ebtikar_ai_task/modules/search/controller/search_view_controller.dart';
export 'package:flutter/cupertino.dart' hide RefreshCallback;
export 'package:ebtikar_ai_task/modules/search/controller/view_single_video_controller.dart';
export 'package:ebtikar_ai_task/modules/settings/widgets/settings_drawer_item.dart';

export 'package:ebtikar_ai_task/modules/search/binding/view_single_video_binding.dart';
export 'package:ebtikar_ai_task/modules/search/view/view_single_video_view.dart';
export 'package:ebtikar_ai_task/resources/widgets/video/side_icons.dart';
export 'package:ebtikar_ai_task/resources/widgets/video/video_content.dart';
export 'package:ebtikar_ai_task/resources/widgets/video/video_loading.dart';
export 'package:ebtikar_ai_task/resources/widgets/video/video_item.dart';
export 'package:ebtikar_ai_task/resources/mixins/responsive_design_breakpoints.dart';
export 'package:ebtikar_ai_task/resources/services/master_functions_service.dart';
export 'package:ebtikar_ai_task/resources/services/shared_prefs_service.dart';
export 'package:ebtikar_ai_task/resources/theme/colors_manager.dart';
export 'package:ebtikar_ai_task/resources/theme/custom_theme_data.dart';
export 'package:ebtikar_ai_task/resources/theme/theme_manager.dart';
export 'package:ebtikar_ai_task/resources/widgets/custom_bottom_sheet_button.dart';
export 'package:ebtikar_ai_task/resources/widgets/main_app_bar.dart';
export 'package:ebtikar_ai_task/resources/widgets/main_button.dart';
export 'package:ebtikar_ai_task/resources/widgets/responsive_design.dart';
export 'package:ebtikar_ai_task/resources/widgets/scale_text.dart';
